### PR TITLE
Add Copyright notice to gradle files

### PR DESCRIPTION
**Pull request by yasith**
- Adding the AOSP copyright notice to gradle files

### CODE REVIEW

**Comment by yasith** [comment]
Current dependencies on/for this PR:
* main
  * **PR #51** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/51" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/google/jetpack-camera-app/51?utm_source=stack-comment).

**Comment by yasith** [comment]
Current dependencies on/for this PR:
* main
  * **PR #51** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/51" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/google/jetpack-camera-app/51?utm_source=stack-comment).

**Comment by yasith** [comment]
Current dependencies on/for this PR:
* main
  * **PR #52** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/52" target="_blank">Graphite</a> 
    * **PR #51** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/51" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/google/jetpack-camera-app/51?utm_source=stack-comment).

**Review by davidjiagoogle — APPROVED** [review]

**Comment by yasith** [comment]
### Merge activity

* **Oct 11, 4:26 PM**: @yasith started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/google/jetpack-camera-app/51).

**Pull request merged**
